[default]
extend-ignore-re = [
    # citation keys
    "@\\w*",
    "<\\w*>",
]

[default.extend-words]
# code stuff
lik = "lik"
# surnames
Yau = "Yau"

[type.sty]
extend-glob = ["*.sty"]
check-file = false

[type.gitignore]
extend-glob = [".gitignore"]
check-file = false

[type.svg]
extend-glob = ["*.svg"]
check-file = false

[type.references]
extend-glob = ["references.yml"]
check-file = false
